services:

  # ----------------------------------------------------------------------------
  # WEBSERVER

  webserver:

    # image: "${DOCKERHUB_USER}/${WEBSERVER_VERSION}:latest"

    build:
      context: ./bin/${WEBSERVER_VERSION}
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        UNAME: ${UNAME}

    command: /bin/bash -c "/usr/local/bin/create-vhosts.sh && exec apache2ctl -D FOREGROUND"

    container_name: "${COMPOSE_PROJECT_NAME}-${WEBSERVER_VERSION}"

    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"

    links:
      - database

    volumes:
      - ${DOCUMENT_ROOT}:${APACHE_DOCUMENT_ROOT}:rw
      - ${SHARED_ROOT}:${APACHE_SHARED_ROOT}:rw
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${SSL_DIR}:/etc/apache2/ssl/
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
      - ${XDEBUG_LOG_DIR}:/var/log/xdebug

    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
      APACHE_SHARED_ROOT: ${APACHE_SHARED_ROOT}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
      UNAME: ${UNAME}
      DOMAIN: ${DOMAIN}
      DOCUMENT_FOLDER: ${DOCUMENT_FOLDER}
      SSL_TYPE: ${SSL_TYPE}
      
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # ----------------------------------------------------------------------------
  # DATABASE

  database:

    # image: "${DOCKERHUB_USER}/${DATABASE_VERSION}:latest"

    build:
      context: ./bin/${DATABASE_VERSION}

    container_name: "${COMPOSE_PROJECT_NAME}-${DATABASE_VERSION}"

    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
      
    volumes:
      - ${MYSQL_INITDB_DIR-./config/initdb}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  
  # ----------------------------------------------------------------------------
  # REDIS

  # redis:
  #   container_name: "${COMPOSE_PROJECT_NAME}-redis"
  #   image: redis:latest
  #   ports:
  #     - "127.0.0.1:${HOST_MACHINE_REDIS_PORT}:6379"
